### ISSUE TITLE
Running 'lago start' in already started environment errors

### ISSUE THREAD

**Issue by ehelms** [lago-project/lago#105]
Running 'lago start' in an already started environment spits out an error and appears to hang the VMs:

```
+ cd environment
+ HOST=satellite.example.com
+ lago start
@ Start Prefix: 
  # Start nets: 
  # Start nets: ERROR (in 0:00:00)
  # Destroy network testenv: 
  # Destroy network testenv: ERROR (in 0:00:00)
@ Start Prefix: ERROR (in 0:00:00)
Error occured, aborting
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 447, in main
    cli_plugins[args.verb].do_run(args)
  File "/usr/lib/python2.7/site-packages/lago/plugins/cli.py", line 180, in do_run
    self._do_run(**vars(args))
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 124, in wrapper
    return func(*args, prefix=lago.Prefix(os.getcwd()), **kwargs)
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 133, in wrapper
    return func(*args, prefix=prefix, **kwargs)
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 155, in do_start
    prefix.start(vm_names=vm_names)
  File "/usr/lib/python2.7/site-packages/lago/__init__.py", line 769, in start
    self.virt_env.start(vm_names=vm_names)
  File "/usr/lib/python2.7/site-packages/lago/virt.py", line 154, in start
    net.start()
  File "/usr/lib/python2.7/site-packages/lago/virt.py", line 368, in start
    brctl.create(self._libvirt_name())
  File "/usr/lib/python2.7/site-packages/lago/brctl.py", line 40, in create
    _brctl('addbr', name)
  File "/usr/lib/python2.7/site-packages/lago/brctl.py", line 29, in _brctl
    raise RuntimeError('brctl %s failed' % command)
RuntimeError: brctl addbr failed
```

**Comment by david-caro** [comment]
Note: This is happens only with bridged networks
