### ISSUE TITLE
Lack of snapshot  throws ugly error

### ISSUE THREAD

**Issue by ehelms** [lago-project/lago#106]
Trying to use the `snapshot` command, and an ugly error is thrown that doesn't help me move forward as a user:

```
@ Create VMs snapshots: ERROR (in 0:00:03)
Error occured, aborting
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 447, in main
    cli_plugins[args.verb].do_run(args)
  File "/usr/lib/python2.7/site-packages/lago/plugins/cli.py", line 180, in do_run
    self._do_run(**vars(args))
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 124, in wrapper
    return func(*args, prefix=lago.Prefix(os.getcwd()), **kwargs)
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 133, in wrapper
    return func(*args, prefix=prefix, **kwargs)
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 182, in do_snapshot
    prefix.create_snapshots(snapshot_name)
  File "/usr/lib/python2.7/site-packages/lago/__init__.py", line 793, in create_snapshots
    self.virt_env.create_snapshots(name)
  File "/usr/lib/python2.7/site-packages/lago/log_utils.py", line 599, in wrapper
    func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/lago/virt.py", line 245, in create_snapshots
    self._vms.values(),
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 87, in invoke_in_parallel
    vt.join_all()
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 45, in _ret_via_queue
    queue.put({'return': func()})
  File "/usr/lib/python2.7/site-packages/lago/virt.py", line 244, in <lambda>
    lambda vm: vm.create_snapshot(name),
  File "/usr/lib/python2.7/site-packages/lago/virt.py", line 834, in create_snapshot
    self._create_live_snapshot(name)
  File "/usr/lib/python2.7/site-packages/lago/virt.py", line 874, in _create_live_snapshot
    libvirt.VIR_DOMAIN_SNAPSHOT_CREATE_QUIESCE,
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 2435, in snapshotCreateXML
    if ret is None:raise libvirtError('virDomainSnapshotCreateXML() failed', dom=self)
libvirtError: Operation not supported: live disk snapshot not supported with this QEMU binary
```

**Comment by david-caro** [comment]
That's the whole dump? Can you attach the logs/lago.log file from the prefix too?

David Caro

El 10/2/2016 23:37, Eric D Helms <notifications@github.com> escribió:

Trying to use the snapshot command, and an ugly error is thrown that doesn't help me move forward as a user:

@ Create VMs snapshots: ERROR (in 0:00:03) Error occured, aborting Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 447, in main cli_plugins[args.verb].do_run(args) File "/usr/lib/python2.7/site-packages/lago/plugins/cli.py", line 180, in do_run self._do_run(**vars(args)) File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 124, in wrapper return func(*args, prefix=lago.Prefix(os.getcwd()), **kwargs) File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 133, in wrapper return func(*args, prefix=prefix, **kwargs) File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 182, in do_snapshot prefix.create_snapshots(snapshot_name) File "/usr/lib/python2.7/site-packages/lago/__init__.py", line 793, in create_snapshots self.virt_env.create_snapshots(name) File "/usr/lib/python2.7/site-packages/lago/log_utils.py", line 599, in wrapper func(*args, **kwargs) File "/usr/lib/python2.7/site-packages/lago/virt.py", line 245, in create_snapshots self._vms.values(), File "/usr/lib/python2.7/site-packages/lago/utils.py", line 87, in invoke_in_parallel vt.join_all() File "/usr/lib/python2.7/site-packages/lago/utils.py", line 45, in _ret_via_queue queue.put({'return': func()}) File "/usr/lib/python2.7/site-packages/lago/virt.py", line 244, in <lambda> lambda vm: vm.create_snapshot(name), File "/usr/lib/python2.7/site-packages/lago/virt.py", line 83

**Comment by ehelms** [comment]
Full output from logs:

```
2016-02-10 18:38:31,196::virt.py::ssh::617::lago.virt::DEBUG::Running 6482df32 on host1.example.com: sync
2016-02-10 18:38:31,219::virt.py::ssh::641::lago.virt::DEBUG::Command 6482df32 on host1.example.com returned with 0
2016-02-10 18:38:31,270::virt.py::ssh::617::lago.virt::DEBUG::Running 648e411a on capsule.example.com: /usr/bin/systemctl status --lines=0 qemu-guest-agent
2016-02-10 18:38:31,303::virt.py::_create_live_snapshot::880::lago.virt::ERROR::Failed to create snapshot init for host1.example.com
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/lago/virt.py", line 874, in _create_live_snapshot
    libvirt.VIR_DOMAIN_SNAPSHOT_CREATE_QUIESCE,
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 2435, in snapshotCreateXML
    if ret is None:raise libvirtError('virDomainSnapshotCreateXML() failed', dom=self)
libvirtError: Operation not supported: live disk snapshot not supported with this QEMU binary
2016-02-10 18:38:31,304::log_utils.py::end_log_task::633::root::ERROR::end task Creating live snapshot named init for host1.example.com
2016-02-10 18:38:31,305::utils.py::_ret_via_queue::47::lago.utils::ERROR::Error while running thread
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 45, in _ret_via_queue
    queue.put({'return': func()})
  File "/usr/lib/python2.7/site-packages/lago/virt.py", line 244, in <lambda>
    lambda vm: vm.create_snapshot(name),
  File "/usr/lib/python2.7/site-packages/lago/virt.py", line 834, in create_snapshot
    self._create_live_snapshot(name)
  File "/usr/lib/python2.7/site-packages/lago/virt.py", line 874, in _create_live_snapshot
    libvirt.VIR_DOMAIN_SNAPSHOT_CREATE_QUIESCE,
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 2435, in snapshotCreateXML
    if ret is None:raise libvirtError('virDomainSnapshotCreateXML() failed', dom=self)
libvirtError: Operation not supported: live disk snapshot not supported with this QEMU binary
2016-02-10 18:38:31,400::virt.py::ssh::641::lago.virt::DEBUG::Command 648e411a on capsule.example.com returned with 0
2016-02-10 18:38:31,400::virt.py::ssh::649::lago.virt::DEBUG::Command 648e411a on capsule.example.com output:
 ● qemu-guest-agent.service - QEMU Guest Agent
   Loaded: loaded (/usr/lib/systemd/system/qemu-guest-agent.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2016-02-10 18:34:06 EST; 4min 23s ago
 Main PID: 468 (qemu-ga)
   CGroup: /system.slice/qemu-guest-agent.service
           └─468 /usr/bin/qemu-ga --method=virtio-serial --path=/dev/virtio-ports/org.qemu.guest_agent.0 --blacklist=guest-file-open guest-file-close guest-file-read guest-file-write guest-file-seek guest-file-flush -F/etc/qemu-ga/fsfreeze-hook
```

In another run it ended up locking up my lago process to the point I had to kill it.

**Comment by ifireball** [comment]
On 11 February 2016 at 00:37, Eric D Helms <notifications@github.com> wrote:

> Trying to use the snapshot command, and an ugly error is thrown that
> doesn't help me move forward as a user:
>
> You need the qemu-kvm-rhev package, the vanilla qemu-kvm shipped with RHEL
is old and buggy...
(There are some issues with just depending on that, because it is not
shipped in RHEL for customers
without RHEV subscriptions)
You can get it from this repo:
http://download.eng.tlv.redhat.com/pub/rhel/rel-eng/repos/rhevh-rhel-7.1-candidate/x86_64/

Or just directly from Brew:
https://brewweb.devel.redhat.com/packageinfo?packageID=35491

On CentOS it is called 'qemu-kvm-ev' and you can get access to it by
enabling the extra repos and then installing 'centos-release-qemu-ev'.

Anyway we need to do better work with this:
https://github.com/lago-project/lago/issues/107
https://github.com/lago-project/lago/issues/108


-- 
*Barak Korren*
bkorren@redhat.com
RHEV-CI Team

**Comment by david-caro** [comment]
Moved to #107
