### ISSUE TITLE
Snapshots should fail gracfully if the running qemu/kvm version does not support them.

### ISSUE THREAD

**Issue by ifireball** [lago-project/lago#108]
Right now we just get a very ugly exception:

```
2016-02-10 18:38:31,196::virt.py::ssh::617::lago.virt::DEBUG::Running 6482df32 on host1.example.com: sync
2016-02-10 18:38:31,219::virt.py::ssh::641::lago.virt::DEBUG::Command 6482df32 on host1.example.com returned with 0
2016-02-10 18:38:31,270::virt.py::ssh::617::lago.virt::DEBUG::Running 648e411a on capsule.example.com: /usr/bin/systemctl status --lines=0 qemu-guest-agent
2016-02-10 18:38:31,303::virt.py::_create_live_snapshot::880::lago.virt::ERROR::Failed to create snapshot init for host1.example.com
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/lago/virt.py", line 874, in _create_live_snapshot
    libvirt.VIR_DOMAIN_SNAPSHOT_CREATE_QUIESCE,
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 2435, in snapshotCreateXML
    if ret is None:raise libvirtError('virDomainSnapshotCreateXML() failed', dom=self)
libvirtError: Operation not supported: live disk snapshot not supported with this QEMU binary
2016-02-10 18:38:31,304::log_utils.py::end_log_task::633::root::ERROR::end task Creating live snapshot named init for host1.example.com
2016-02-10 18:38:31,305::utils.py::_ret_via_queue::47::lago.utils::ERROR::Error while running thread
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 45, in _ret_via_queue
    queue.put({'return': func()})
  File "/usr/lib/python2.7/site-packages/lago/virt.py", line 244, in <lambda>
    lambda vm: vm.create_snapshot(name),
  File "/usr/lib/python2.7/site-packages/lago/virt.py", line 834, in create_snapshot
    self._create_live_snapshot(name)
  File "/usr/lib/python2.7/site-packages/lago/virt.py", line 874, in _create_live_snapshot
    libvirt.VIR_DOMAIN_SNAPSHOT_CREATE_QUIESCE,
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 2435, in snapshotCreateXML
    if ret is None:raise libvirtError('virDomainSnapshotCreateXML() failed', dom=self)
libvirtError: Operation not supported: live disk snapshot not supported with this QEMU binary
2016-02-10 18:38:31,400::virt.py::ssh::641::lago.virt::DEBUG::Command 648e411a on capsule.example.com returned with 0
2016-02-10 18:38:31,400::virt.py::ssh::649::lago.virt::DEBUG::Command 648e411a on capsule.example.com output:
 ● qemu-guest-agent.service - QEMU Guest Agent
   Loaded: loaded (/usr/lib/systemd/system/qemu-guest-agent.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2016-02-10 18:34:06 EST; 4min 23s ago
 Main PID: 468 (qemu-ga)
   CGroup: /system.slice/qemu-guest-agent.service
           └─468 /usr/bin/qemu-ga --method=virtio-serial --path=/dev/virtio-ports/org.qemu.guest_agent.0 --blacklist=guest-file-open guest-file-close guest-file-read guest-file-write guest-file-seek guest-file-flush -F/etc/qemu-ga/fsfreeze-hook
```

**Comment by david-caro** [comment]
Not sure this is wise... there are a lot of errors that might be raised by libvirt, this being just one of them, why should it have a special treatment?

**Comment by ifireball** [comment]
It special because its is the result of a dependency issue, not user misconfiguration. We could alternatively depend on qemu-kvm-ev on el7

**Comment by david-caro** [comment]
that sounds more reasonable, same as #107
