### ISSUE TITLE
Duplicate ID error when adding second disk

### ISSUE THREAD

**Issue by ehelms** [lago-project/lago#113]
I have attempted to add a secondary disk the following way:

```
            "disks": [
                {
                    "template_name": "rhel7_2_host",
                    "type": "template",
                    "name": "root",
                    "dev": "vda",
                    "format": "qcow2"
                },
                {
                    "name": "root1",
                    "type": "empty",
                    "dev": "vda1",
                    "format": "raw",
                    "size": "100G"
                }
            ],
```

Error output:

```
[jenkins@sat-r220-08 environment]$ lago start
@ Start Prefix: 
  # Start nets: 
    * Create network testenv: 
    * Create network testenv: Success (in 0:00:00)
    * Create network sat: 
    * Create network sat: Success (in 0:00:00)
  # Start nets: Success (in 0:00:00)
  # Start vms: 
    * Starting VM satellite.example.com: 
libvirt: QEMU Driver error : internal error: process exited while connecting to monitor: qemu-kvm: -drive file=/home/jenkins/sat-deploy/lago/environment/images/satellite.example.com_root1.raw,if=none,id=drive-virtio-disk0,format=raw: Duplicate ID 'drive-virtio-disk0' for drive
    * Starting VM satellite.example.com: ERROR (in 0:00:00)
  # Start vms: ERROR (in 0:00:00)
  # Destroy network sat: 
  # Destroy network sat: ERROR (in 0:00:00)
  # Destroy network testenv: 
  # Destroy network testenv: ERROR (in 0:00:00)
@ Start Prefix: ERROR (in 0:00:00)
Error occured, aborting
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 447, in main
    cli_plugins[args.verb].do_run(args)
  File "/usr/lib/python2.7/site-packages/lago/plugins/cli.py", line 180, in do_run
    self._do_run(**vars(args))
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 124, in wrapper
    return func(*args, prefix=lago.Prefix(os.getcwd()), **kwargs)
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 133, in wrapper
    return func(*args, prefix=prefix, **kwargs)
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 155, in do_start
    prefix.start(vm_names=vm_names)
  File "/usr/lib/python2.7/site-packages/lago/__init__.py", line 769, in start
    self.virt_env.start(vm_names=vm_names)
  File "/usr/lib/python2.7/site-packages/lago/virt.py", line 159, in start
    vm.start()
  File "/usr/lib/python2.7/site-packages/lago/virt.py", line 816, in start
    self._env.libvirt_con.createXML(self._libvirt_xml())
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 3611, in createXML
    if ret is None:raise libvirtError('virDomainCreateXML() failed', conn=self)
libvirtError: internal error: process exited while connecting to monitor: qemu-kvm: -drive file=/home/jenkins/sat-deploy/lago/environment/images/satellite.example.com_root1.raw,if=none,id=drive-virtio-disk0,format=raw: Duplicate ID 'drive-virtio-disk0' for drive
```

**Comment by ifireball** [comment]
you should probably tell it to add disk as vdb, but yeah, an error message
telling you that would be nice
בתאריך 12 בפבר׳ 2016 18:33,‏ "Eric D Helms" <notifications@github.com> כתב:

**Comment by david-caro** [comment]
this looks like something that the spec parser should catch on init
