### ISSUE TITLE
Tests get stuck in 'Waiting for ssh connectivity'

### ISSUE THREAD

**Issue by mykaul** [lago-project/lago#179]
After upgrade to 0.12, the tests never completed:
```
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
  # Revert VMs snapshots: 
    * [Thread-2] Reverting lago_basic_suite_3_6_host1 to snapshot ovirt-clean: 
    * [Thread-3] Reverting lago_basic_suite_3_6_engine to snapshot ovirt-clean: 
    * [Thread-4] Reverting lago_basic_suite_3_6_storage-iscsi to snapshot ovirt-clean: 
    * [Thread-5] Reverting lago_basic_suite_3_6_storage-nfs to snapshot ovirt-clean: 
    * [Thread-6] Reverting lago_basic_suite_3_6_host0 to snapshot ovirt-clean: 
    * [Thread-4] Reverting lago_basic_suite_3_6_storage-iscsi to snapshot ovirt-clean: Success (in 0:00:02)
    * [Thread-3] Reverting lago_basic_suite_3_6_engine to snapshot ovirt-clean: Success (in 0:00:02)
    * [Thread-5] Reverting lago_basic_suite_3_6_storage-nfs to snapshot ovirt-clean: Success (in 0:00:02)
    * [Thread-2] Reverting lago_basic_suite_3_6_host1 to snapshot ovirt-clean: Success (in 0:00:02)
    * [Thread-6] Reverting lago_basic_suite_3_6_host0 to snapshot ovirt-clean: Success (in 0:00:02)
  # Revert VMs snapshots: Success (in 0:00:02)
  # Wait for ssh connectivity: 


^C  # Wait for ssh connectivity: ERROR (in 0:24:02)
  # Results located at /home/zram/3.6/default/nosetests-004_basic_sanity.py.xml
@ Run test: 004_basic_sanity.py: ERROR (in 0:24:04)
^CTraceback (most recent call last):
  File "/usr/bin/lagocli", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 619, in main
    cli_plugins[args.verb].do_run(args)
  File "/usr/lib/python2.7/site-packages/ovirtlago/cmd.py", line 248, in do_run
    self.cli_plugins[args.ovirtverb].do_run(args)
  File "/usr/lib/python2.7/site-packages/lago/plugins/cli.py", line 180, in do_run
    self._do_run(**vars(args))
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 501, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 512, in wrapper
    return func(*args, prefix=prefix, **kwargs)
  File "/usr/lib/python2.7/site-packages/ovirtlago/cmd.py", line 101, in do_ovirt_runtest
    if not prefix.run_test(test_file):
  File "/usr/lib/python2.7/site-packages/ovirtlago/__init__.py", line 52, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib64/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/lib/python2.7/site-packages/ovirtlago/utils.py", line 122, in repo_server_context
    server.shutdown()
  File "/usr/lib64/python2.7/SocketServer.py", line 251, in shutdown
    self.__is_shut_down.wait()
  File "/usr/lib64/python2.7/threading.py", line 624, in wait
    self.__cond.wait(timeout, balancing)
  File "/usr/lib64/python2.7/threading.py", line 340, in wait
    waiter.acquire()
```

log:
```
2016-03-13 13:15:29,982::log_utils.py::__exit__::581::lago.virt::INFO::Success (in 0:00:01)
2016-03-13 13:15:29,983::log_utils.py::__exit__::581::lago.virt::INFO::    * [Thread-4] Reverting lago_basic_suite_3_6_storage-iscsi to snapshot ovirt-clean: Success (in 0:00:02)
2016-03-13 13:15:29,983::log_utils.py::__exit__::581::lago.virt::INFO::Success (in 0:00:00)
2016-03-13 13:15:29,983::log_utils.py::__exit__::581::lago.virt::INFO::Success (in 0:00:01)
2016-03-13 13:15:29,983::log_utils.py::__exit__::581::lago.virt::INFO::Success (in 0:00:01)
2016-03-13 13:15:29,983::log_utils.py::__exit__::581::lago.virt::INFO::    * [Thread-3] Reverting lago_basic_suite_3_6_engine to snapshot ovirt-clean: Success (in 0:00:02)
2016-03-13 13:15:29,984::log_utils.py::__exit__::581::lago.virt::INFO::    * [Thread-5] Reverting lago_basic_suite_3_6_storage-nfs to snapshot ovirt-clean: Success (in 0:00:02)
2016-03-13 13:15:29,984::log_utils.py::__exit__::581::lago.virt::INFO::    * [Thread-2] Reverting lago_basic_suite_3_6_host1 to snapshot ovirt-clean: Success (in 0:00:02)
2016-03-13 13:15:29,988::log_utils.py::__exit__::581::lago.virt::INFO::Success (in 0:00:01)
2016-03-13 13:15:29,988::log_utils.py::__exit__::581::lago.virt::INFO::    * [Thread-6] Reverting lago_basic_suite_3_6_host0 to snapshot ovirt-clean: Success (in 0:00:02)
2016-03-13 13:15:29,989::log_utils.py::__exit__::581::lago.virt::INFO::  # Revert VMs snapshots: Success (in 0:00:02)
2016-03-13 13:15:29,989::log_utils.py::__enter__::574::ovirtlago::INFO::  # Wait for ssh connectivity: 
2016-03-13 13:15:47,945::virt.py::ssh::679::lago.virt::DEBUG::Running eff682b4 on lago_basic_suite_3_6_storage-iscsi: true
2016-03-13 13:15:48,378::virt.py::ssh::703::lago.virt::DEBUG::Command eff682b4 on lago_basic_suite_3_6_storage-iscsi returned with 0
2016-03-13 13:15:53,745::virt.py::ssh::679::lago.virt::DEBUG::Running f36b6892 on lago_basic_suite_3_6_engine: true
2016-03-13 13:15:53,883::virt.py::ssh::703::lago.virt::DEBUG::Command f36b6892 on lago_basic_suite_3_6_engine returned with 0
2016-03-13 13:15:56,790::virt.py::ssh::679::lago.virt::DEBUG::Running f53c24f4 on lago_basic_suite_3_6_host1: true
2016-03-13 13:15:57,031::virt.py::ssh::703::lago.virt::DEBUG::Command f53c24f4 on lago_basic_suite_3_6_host1 returned with 0
2016-03-13 13:15:57,444::virt.py::ssh::679::lago.virt::DEBUG::Running f59fe0d4 on lago_basic_suite_3_6_storage-nfs: true
2016-03-13 13:15:57,604::virt.py::ssh::703::lago.virt::DEBUG::Command f59fe0d4 on lago_basic_suite_3_6_storage-nfs returned with 0
2016-03-13 13:39:32,619::log_utils.py::end_log_task::632::root::ERROR::  # Wait for ssh connectivity: ERROR (in 0:24:02)
2016-03-13 13:39:32,620::__init__.py::run_test::448::ovirtlago::INFO::  # Results located at /home/zram/3.6/default/nosetests-004_basic_sanity.py.xml
2016-03-13 13:39:32,620::log_utils.py::__exit__::581::ovirtlago::INFO::@ Run test: 004_basic_sanity.py: ERROR (in 0:24:04)
2016-03-13 13:41:28,882::virt.py::ssh::679::lago.virt::DEBUG::Running 866edcc0 on lago_basic_suite_3_6_host1: true
2016-03-13 13:41:29,006::virt.py::ssh::703::lago.virt::DEBUG::Command 866edcc0 on lago_basic_suite_3_6_host1 returned with 0
```

the problem is probably with host0, which cannot be SSH'ed to (and has no timeout to this?):
```
mini@ykaul-mini:/home/zram/3.6/current$ lagocli shell lago_basic_suite_3_6_host0 
^CTraceback (most recent call last):
  File "/usr/bin/lagocli", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 619, in main
    cli_plugins[args.verb].do_run(args)
  File "/usr/lib/python2.7/site-packages/lago/plugins/cli.py", line 180, in do_run
    self._do_run(**vars(args))
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 501, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 512, in wrapper
    return func(*args, prefix=prefix, **kwargs)
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 307, in do_shell
    host.wait_for_ssh()
  File "/usr/lib/python2.7/site-packages/lago/virt.py", line 725, in wait_for_ssh
    ret, _, _ = self.ssh(['true'])
  File "/usr/lib/python2.7/site-packages/lago/virt.py", line 668, in ssh
    client = self._get_ssh_client()
  File "/usr/lib/python2.7/site-packages/lago/virt.py", line 642, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/lago/virt.py", line 656, in _get_ssh_client
    timeout=1,
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 251, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib/python2.7/site-packages/paramiko/util.py", line 270, in retry_on_signal
    return function()
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 251, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib64/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt
```

**Comment by david-caro** [comment]
iirc there is a timeout, but it was huge. Did you try the console? What was the host state on libvirt? Was it down? paused? (that might happen if your host ran out of mem)

**Comment by mykaul** [comment]
Reproduced. I can't SSH to it - not even from a different VM. libvirt thinks its up:
virsh # dominfo 5f379e4e-lago_basic_suite_3_6_host0
Id:             116
Name:           5f379e4e-lago_basic_suite_3_6_host0
UUID:           54df9109-c434-479a-89ae-e94335db5c24
OS Type:        hvm
State:          running
CPU(s):         2
CPU time:       26.4s
Max memory:     8387584 KiB
Used memory:    8387584 KiB
Persistent:     no
Autostart:      disable
Managed save:   no
Security model: none
Security DOI:   0


I'm not out of space. Nothing suspicious from libvirt qemu logs.

The interface is up:
virsh # domiflist 116
Interface  Type       Source     Model       MAC
-------------------------------------------------------
vnet1      network    5f37-930e31b9b9 virtio      54:52:c0:a8:c8:06

virsh # domif-getlink 116 vnet1

But certainly something is wrong with the networking - see the 'rx_drop' !
virsh # domiflist 116
Interface  Type       Source     Model       MAC
-------------------------------------------------------
vnet1      network    5f37-930e31b9b9 virtio      54:52:c0:a8:c8:06

virsh # domiflist 118
Interface  Type       Source     Model       MAC
-------------------------------------------------------
vnet2      network    5f37-930e31b9b9 virtio      54:52:c0:a8:c8:04

virsh # domifstat 116 vnet1
vnet1 rx_bytes 19435
vnet1 rx_packets 258
vnet1 rx_errs 0
vnet1 rx_drop 3339
vnet1 tx_bytes 5270
vnet1 tx_packets 38
vnet1 tx_errs 0
vnet1 tx_drop 0

virsh # domifstat 118 vnet2
vnet2 rx_bytes 196286
vnet2 rx_packets 4164
vnet2 rx_errs 0
vnet2 rx_drop 0
vnet2 tx_bytes 13665
vnet2 tx_packets 107
vnet2 tx_errs 0
vnet2 tx_drop 0

**Comment by david-caro** [comment]
can you try 'lago console' or 'virsh console' (it's the same in the end) and see if you can get a console to the machine?

**Comment by mykaul** [comment]
Console doesn't seem to work for any of them (host0, host1, engine) - perhaps I'm doing something wrong?
mini@ykaul-mini:~$ lagocli --prefix-path=/home/zram/3.6/current console  lago_basic_suite_3_6_host1
Connected to domain 5f379e4e-lago_basic_suite_3_6_host1
Escape character is ^]

mini@ykaul-mini:~$ lagocli --prefix-path=/home/zram/3.6/current console  lago_basic_suite_3_6_engine
Connected to domain 5f379e4e-lago_basic_suite_3_6_engine
Escape character is ^]

**Comment by david-caro** [comment]
I suppose then that you are using the old images, not the new el7-base ones :/

**Comment by mykaul** [comment]
On Mon, Mar 14, 2016 at 4:04 PM, David Caro <notifications@github.com>
wrote:

> I suppose then that you are using the old images, not the new el7-base
> ones :/
>
mini@ykaul-mini:/home/lagostore$ ls -ltr
total 13091268
-rw-rw-r-- 1 mini lago           56 מרץ  7 08:15
in_office_repo:storage-nfs:v1.metadata
-rw-rw-r-- 1 mini lago           40 מרץ  7 08:15
in_office_repo:storage-nfs:v1.hash
-rw-r--r-- 1 qemu qemu  10737418240 מרץ  7 08:15
in_office_repo:storage-nfs:v1
-rw-rw-r-- 1 mini lago            2 מרץ  7 08:15
in_office_repo:storage-nfs-export:v1.metadata
-rw-rw-r-- 1 mini lago           40 מרץ  7 08:15
in_office_repo:storage-nfs-export:v1.hash
-rw-r--r-- 1 qemu qemu 107374182400 מרץ  7 08:15
in_office_repo:storage-nfs-export:v1
-rw-rw-r-- 1 mini lago           55 מרץ  7 08:16
in_office_repo:centos7_host:v5.metadata
-rw-rw-r-- 1 mini lago           40 מרץ  7 08:16
in_office_repo:centos7_host:v5.hash
-rw-r--r-- 1 qemu qemu  53687091200 מרץ  7 08:16
in_office_repo:centos7_host:v5
-rw-rw-r-- 1 mini lago           56 מרץ  7 15:08
in_office_repo:storage-iscsi:v1.metadata
-rw-rw-r-- 1 mini lago           40 מרץ  7 15:08
in_office_repo:storage-iscsi:v1.hash
-rw-r--r-- 1 qemu qemu  10737418240 מרץ  7 15:08
in_office_repo:storage-iscsi:v1
-rw-rw-r-- 1 mini mini           55 מרץ  8 23:13
in_office_repo:centos7_engine:v5.metadata
-rw-rw-r-- 1 mini mini           40 מרץ  8 23:13
in_office_repo:centos7_engine:v5.hash
-rw-r--r-- 1 qemu qemu  53687091200 מרץ  8 23:13
in_office_repo:centos7_engine:v5
-rw-rw-r-- 1 mini mini           55 מרץ  9 13:27
in_office_repo:centos6_engine:v2.metadata
-rw-rw-r-- 1 mini mini           40 מרץ  9 13:27
in_office_repo:centos6_engine:v2.hash
-rw-r--r-- 1 qemu qemu  42949672960 מרץ  9 13:27
in_office_repo:centos6_engine:v2
-rw-rw-r-- 1 mini mini          133 מרץ 13 17:10
in_office_repo:centos7_engine:v5.users
-rw-rw-r-- 1 mini lago          209 מרץ 14 16:05
in_office_repo:storage-iscsi:v1.users
-rw-rw-r-- 1 mini mini          130 מרץ 14 16:05
in_office_repo:centos6_engine:v2.users
-rw-rw-r-- 1 mini lago          209 מרץ 14 16:05
in_office_repo:storage-nfs:v1.users
-rw-rw-r-- 1 mini lago          209 מרץ 14 16:05
in_office_repo:storage-nfs-export:v1.users
-rw-rw-r-- 1 mini lago          209 מרץ 14 16:05
in_office_repo:centos7_host:v5.users

**Comment by david-caro** [comment]
On 03/14 07:12, Yaniv Kaul wrote:
> On Mon, Mar 14, 2016 at 4:04 PM, David Caro <notifications@github.com>
> wrote:
> 
> > I suppose then that you are using the old images, not the new el7-base
> > ones :/
> >
> mini@ykaul-mini:/home/lagostore$ ls -ltr
> total 13091268


Yep, those are the old ones, the new ones are used by the patch (under work):
   https://gerrit.ovirt.org/#/c/53534/


The new images do allow serial console by default

> -rw-rw-r-- 1 mini lago           56 מרץ  7 08:15
> in_office_repo:storage-nfs:v1.metadata
> -rw-rw-r-- 1 mini lago           40 מרץ  7 08:15
> in_office_repo:storage-nfs:v1.hash
> -rw-r--r-- 1 qemu qemu  10737418240 מרץ  7 08:15
> in_office_repo:storage-nfs:v1
> -rw-rw-r-- 1 mini lago            2 מרץ  7 08:15
> in_office_repo:storage-nfs-export:v1.metadata
> -rw-rw-r-- 1 mini lago           40 מרץ  7 08:15
> in_office_repo:storage-nfs-export:v1.hash
> -rw-r--r-- 1 qemu qemu 107374182400 מרץ  7 08:15
> in_office_repo:storage-nfs-export:v1
> -rw-rw-r-- 1 mini lago           55 מרץ  7 08:16
> in_office_repo:centos7_host:v5.metadata
> -rw-rw-r-- 1 mini lago           40 מרץ  7 08:16
> in_office_repo:centos7_host:v5.hash
> -rw-r--r-- 1 qemu qemu  53687091200 מרץ  7 08:16
> in_office_repo:centos7_host:v5
> -rw-rw-r-- 1 mini lago           56 מרץ  7 15:08
> in_office_repo:storage-iscsi:v1.metadata
> -rw-rw-r-- 1 mini lago           40 מרץ  7 15:08
> in_office_repo:storage-iscsi:v1.hash
> -rw-r--r-- 1 qemu qemu  10737418240 מרץ  7 15:08
> in_office_repo:storage-iscsi:v1
> -rw-rw-r-- 1 mini mini           55 מרץ  8 23:13
> in_office_repo:centos7_engine:v5.metadata
> -rw-rw-r-- 1 mini mini           40 מרץ  8 23:13
> in_office_repo:centos7_engine:v5.hash
> -rw-r--r-- 1 qemu qemu  53687091200 מרץ  8 23:13
> in_office_repo:centos7_engine:v5
> -rw-rw-r-- 1 mini mini           55 מרץ  9 13:27
> in_office_repo:centos6_engine:v2.metadata
> -rw-rw-r-- 1 mini mini           40 מרץ  9 13:27
> in_office_repo:centos6_engine:v2.hash
> -rw-r--r-- 1 qemu qemu  42949672960 מרץ  9 13:27
> in_office_repo:centos6_engine:v2
> -rw-rw-r-- 1 mini mini          133 מרץ 13 17:10
> in_office_repo:centos7_engine:v5.users
> -rw-rw-r-- 1 mini lago          209 מרץ 14 16:05
> in_office_repo:storage-iscsi:v1.users
> -rw-rw-r-- 1 mini mini          130 מרץ 14 16:05
> in_office_repo:centos6_engine:v2.users
> -rw-rw-r-- 1 mini lago          209 מרץ 14 16:05
> in_office_repo:storage-nfs:v1.users
> -rw-rw-r-- 1 mini lago          209 מרץ 14 16:05
> in_office_repo:storage-nfs-export:v1.users
> -rw-rw-r-- 1 mini lago          209 מרץ 14 16:05
> in_office_repo:centos7_host:v5.users
> 
> 
> 
> 
> 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/lago-project/lago/issues/179#issuecomment-196322059>.
> >
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/lago-project/lago/issues/179#issuecomment-196324261

-- 
David Caro

Red Hat S.L.
Continuous Integration Engineer - EMEA ENG Virtualization R&D

Tel.: +420 532 294 605
Email: dcaro@redhat.com
IRC: dcaro|dcaroest@{freenode|oftc|redhat}
Web: www.redhat.com
RHT Global #: 82-62605

**Comment by eedri** [comment]
Can we create an ovirt-system-tests Bug for this patch? so we'll track the progress there and we'll have better documentation on the issue?
