### ISSUE TITLE
"make clean" and "make rpm" targets fail on current (2016-05-24) master

### ISSUE THREAD

**Issue by iankko** [lago-project/lago#264]
If [python-dulwich](https://admin.fedoraproject.org/pkgdb/package/rpms/python-dulwich/) package isn't installed on the system, the ```make clean``` and ```make rpm``` lago Makefile targets fail with python traceback as follows:
```
git clone https://github.com/lago-project/lago.git
cd lago/
$ make clean
Traceback (most recent call last):
  File "scripts/version_manager.py", line 10, in <module>
    import dulwich.repo
ImportError: No module named dulwich.repo
Traceback (most recent call last):
  File "scripts/version_manager.py", line 10, in <module>
    import dulwich.repo
ImportError: No module named dulwich.repo
Traceback (most recent call last):
  File "scripts/version_manager.py", line 10, in <module>
    import dulwich.repo
ImportError: No module named dulwich.repo
python setup.py clean
Traceback (most recent call last):
  File "setup.py", line 60, in <module>
    os.environ['PBR_VERSION'] = get_version()
  File "setup.py", line 46, in get_version
    [version_manager, project_dir, 'version']
  File "setup.py", line 17, in check_output
    (args, proc.returncode, stdout, stderr)
RuntimeError: Failed to run ['./scripts/version_manager.py', '.', 'version']
rc=1
stdout=
stderr=Traceback (most recent call last):
  File "./scripts/version_manager.py", line 10, in <module>
    import dulwich.repo
ImportError: No module named dulwich.repo

Makefile:100: recipe for target 'clean' failed
make: *** [clean] Error 1
```

```
$ make rpm
Traceback (most recent call last):
  File "scripts/version_manager.py", line 10, in <module>
    import dulwich.repo
ImportError: No module named dulwich.repo
Traceback (most recent call last):
  File "scripts/version_manager.py", line 10, in <module>
    import dulwich.repo
ImportError: No module named dulwich.repo
Traceback (most recent call last):
  File "scripts/version_manager.py", line 10, in <module>
    import dulwich.repo
ImportError: No module named dulwich.repo
Traceback (most recent call last):
  File "scripts/version_manager.py", line 10, in <module>
    import dulwich.repo
ImportError: No module named dulwich.repo
LAGO_VERSION= python setup.py sdist --dist-dir /home/iankko/lago/dist
Traceback (most recent call last):
  File "setup.py", line 60, in <module>
    os.environ['PBR_VERSION'] = get_version()
  File "setup.py", line 46, in get_version
    [version_manager, project_dir, 'version']
  File "setup.py", line 17, in check_output
    (args, proc.returncode, stdout, stderr)
RuntimeError: Failed to run ['./scripts/version_manager.py', '.', 'version']
rc=1
stdout=
stderr=Traceback (most recent call last):
  File "./scripts/version_manager.py", line 10, in <module>
    import dulwich.repo
ImportError: No module named dulwich.repo

Makefile:74: recipe for target 'python-sdist' failed
make: *** [python-sdist] Error 1
```

Assuming the reason being just the ```python-dulwich``` (and maybe also other packages) aren't installed on the specific system.

But maybe it would be possible to fail more gracefully if the required RPMs (python modules) aren't installed (request the user to install them instead of traceback).

**Comment by david-caro** [comment]
In lago, the entry point to create artifacts is not the 'make rpm' target, but the automation/build_artifacts.sh, as we are using the ovirt ci-standards:

  http://ovirt-infra-docs.readthedocs.io/en/latest/CI/Build_and_test_standards.html#build-artifacts-sh

You are also very encouraged to use mock_runner.sh to run that script:
    http://ovirt-infra-docs.readthedocs.io/en/latest/CI/Build_and_test_standards.html#testing-the-scripts-locally

**Comment by david-caro** [comment]
More info on how to use mock_runner.sh with lago:
    http://lago.readthedocs.io/en/latest/Env_Setup.html

**Comment by david-caro** [comment]
Probably have to put more emphasis on that in the docs... or get finally rid of the makefile
