### ISSUE TITLE
lago destroy doesn't work when init filed

### ISSUE THREAD

**Issue by kivio** [lago-project/lago#307]
I have problem with finish lago init job.  (it hangs on downloading template without any timeout exception)
If i break this process and want to clear environment lago destroy raise exception. 

```
[kivio@centos lago-test]$ lago destroy
current session does not belong to lago group.
Error occured, aborting
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 691, in main
    cli_plugins[args.verb].do_run(args)
  File "/usr/lib/python2.7/site-packages/lago/plugins/cli.py", line 180, in do_run
    self._do_run(**vars(args))
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 471, in wrapper
    workdir_path = workdir_class.resolve_workdir_path(workdir_path)
  File "/usr/lib/python2.7/site-packages/lago/workdir.py", line 375, in resolve_workdir_path
    os.path.abspath(start_path)
RuntimeError: Unable to find workdir for /home/kivio/lago-test
```

Only one way to retry it is manually removing .lago directory.

**Comment by nvgoldin** [comment]
Hi @kivio , can you please provide a way to replicate the issue?

**Comment by nvgoldin** [comment]
OK - re-read what you wrote and I understand what you mean. I'm changing the title, as this will happen with any verb, not only 'destory', the problem is that when ``lago init`` fails it pollutes the enviornment and currently the only solution is to delete manually the ``.lago`` directory. A solution would be to delete it when ``init`` fails. Fixing it require extra-attention to the corner-cases(for example running ``init`` twice in a row)
