### ISSUE TITLE
Explain why the lock to Lago's 'store' / 'reposync' cannot be acquired

### ISSUE THREAD

**Issue by gbenhaim** [lago-project/lago#357]
Current stack trace when the lock cannot be acquired due to permissions issue:

```
@ Create prefix internal repo: 
  # Syncing remote repos locally (this might take some time): 
    * Acquiring lock for /var/lib/lago/reposync/repolock: 
    * Acquiring lock for /var/lib/lago/reposync/repolock: ERROR (in 0:00:00)
  # Syncing remote repos locally (this might take some time): ERROR (in 0:00:00)
@ Create prefix internal repo: ERROR (in 0:00:00)
Error occured, aborting
Traceback (most recent call last):
  File "/home/gbenhaim/lago/ovirtlago/cmd.py", line 259, in do_run
    self.cli_plugins[args.ovirtverb].do_run(args)
  File "/home/gbenhaim/lago/lago/plugins/cli.py", line 180, in do_run
    self._do_run(**vars(args))
  File "/home/gbenhaim/lago/lago/utils.py", line 490, in wrapper
    return func(*args, **kwargs)
  File "/home/gbenhaim/lago/lago/utils.py", line 501, in wrapper
    return func(*args, prefix=prefix, **kwargs)
  File "/home/gbenhaim/lago/ovirtlago/cmd.py", line 177, in do_ovirt_reposetup
    custom_sources=custom_sources,
  File "/home/gbenhaim/lago/lago/log_utils.py", line 615, in wrapper
    return func(*args, **kwargs)
  File "/home/gbenhaim/lago/ovirtlago/__init__.py", line 288, in prepare_repo
    repos,
  File "/home/gbenhaim/lago/ovirtlago/reposetup.py", line 113, in sync_rpm_repository
    with LockFile(lock_path, timeout=180):
  File "/home/gbenhaim/lago/lago/utils.py", line 381, in __enter__
    self.lock.acquire()
  File "/usr/lib/python2.7/site-packages/lockfile/linklockfile.py", line 20, in acquire
    raise LockFailed("failed to create %s" % self.unique_name)
LockFailed: failed to create /var/lib/lago/reposync/gbenhaim.tlv.csb-b6f01740.24232
```

**Comment by eedri** [comment]
@gbenhaim any update on this? does it mean we can't run Lago on CSB w/o sudo?

**Comment by gbenhaim** [comment]
This issue was fixed in https://github.com/lago-project/lago/pull/583 that is part of v0.40.
There are some reasons for a failure in acquiring the lock (taken from the exception):        

```
         Failed to acquire a lock for store {}.
                This failure can be caused by several reasons:
                1. Another 'lago' environment is using the store.
                2. A stale lock was left in the store.
                3. You don't have R/W permissions to the store.
```

About permissions, the group of the store directory should be ```lago``` (we define it when installing using rpm), and the user who runs lago should be in this group, thus sudo is not needed.

When installing from pip we instruct the user to define himself as the owner of ```/var/lib/lago```, so sudo is not needed in this flow also.

**Comment by gbenhaim** [comment]
Fixed in https://github.com/lago-project/lago/pull/583

**Comment by eedri** [comment]
I think the issue that is causing the failure is #683 as we talked, when using LDAP user.

**Comment by eedri** [comment]
https://github.com/lago-project/lago/issues/638

**Comment by gbenhaim** [comment]
Reopen this issue since https://github.com/lago-project/lago/pull/583 fixed only the subnet store.
