### ISSUE TITLE
lago will init a prefix with domains with empty name

### ISSUE THREAD

**Issue by david-caro** [lago-project/lago#36]
Just use "" as the domain name, it will create the prefix and fail on doing anything else, it should at least warn

**Comment by iankko** [comment]
The case of domain having empty name ('') and referencing a network is handled in the above commit.
Currently trying to find out if there are other code paths yet, that could be reached (besides starting the network one), that could also lead to unhandled exception.

Have tried the case of empty domain without referencing a network (json entry completely missing the ```nics``` entry), and this gives the following traceback:
```
Error occured, aborting
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 691, in main
    cli_plugins[args.verb].do_run(args)
  File "/usr/lib/python2.7/site-packages/lago/plugins/cli.py", line 180, in do_run
    self._do_run(**vars(args))
  File "/usr/lib/python2.7/site-packages/lago/log_utils.py", line 615, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 181, in do_init
    do_bootstrap=not skip_bootstrap,
  File "/usr/lib/python2.7/site-packages/lago/prefix.py", line 823, in virt_conf_from_stream
    do_bootstrap=do_bootstrap,
  File "/usr/lib/python2.7/site-packages/lago/prefix.py", line 943, in virt_conf
    self.virt_env.bootstrap()
  File "/usr/lib/python2.7/site-packages/lago/virt.py", line 162, in bootstrap
    utils.invoke_in_parallel(lambda vm: vm.bootstrap(), self._vms.values())
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 100, in invoke_in_parallel
    vt.join_all()
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 58, in _ret_via_queue
    queue.put({'return': func()})
  File "/usr/lib/python2.7/site-packages/lago/virt.py", line 162, in <lambda>
    utils.invoke_in_parallel(lambda vm: vm.bootstrap(), self._vms.values())
  File "/usr/lib/python2.7/site-packages/lago/virt.py", line 1201, in bootstrap
    for index, nic in enumerate(self._spec['nics'])
KeyError: 'nics'
```

Not sure if this should be handled within this issue too, within another one, or completely ignored (since unlikely to happen). Will also investigate other code paths that could be possibly reached via empty domain.

**Comment by david-caro** [comment]
I think that the check of the domain name being empty should be done before anything else, and just break before running any other code. There's no reason to specify an empty domain name that I can think of
