### ISSUE TITLE
ovirtlago :: lago.log contains misleading ERROR collecting arifacts

### ISSUE THREAD

**Issue by landgraf** [lago-project/lago#414]
lago.log contains misleading ERROR collecting arifacts while the problem is in tests itself.

**Comment by landgraf** [comment]
Example:

2017-01-04 02:33:49,094::log_utils.py::__exit__::599::lago.prefix::INFO::[32mSuccess[0m (in 0:00:01)
2017-01-04 02:33:49,301::log_utils.py::__exit__::599::lago.prefix::INFO::[32mSuccess[0m (in 0:00:02)
2017-01-04 02:33:49,301::log_utils.py::__exit__::599::lago.prefix::INFO::[32mSuccess[0m (in 0:00:02)
2017-01-04 02:33:49,302::log_utils.py::end_log_task::655::root::ERROR::    * Collect artifacts: [31mERROR[0m (in 0:00:02)
2017-01-04 02:33:49,302::log_utils.py::end_log_task::655::root::ERROR::    * Collect artifacts: [31mERROR[0m (in 0:00:02)
2017-01-04 02:33:49,302::log_utils.py::end_log_task::655::nose::INFO::  # vm_run: [31mERROR[0m (in 0:03:08)
2017-01-04 02:33:49,302::log_utils.py::end_log_task::655::nose::INFO::  # vm_run: [31mERROR[0m (in 0:03:08)
2017-01-04 02:33:49,303::log_utils.py::start_log_task::640::nose::INFO::  # snapshots_merge: [0m[0m
2017-01-04 02:33:49,303::log_utils.py::start_log_task::640::nose::INFO::  # snapshots_merge: [0m[0m
2017-01-04 02:44:30,422::utils.py::_ret_via_queue::57::lago.utils::ERROR::Error while running thread
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 55, in _ret_via_queue
    queue.put({'return': func()})
  File "/home/jenkins/workspace/ovirt_4.1_system-tests/ovirt-system-tests/basic-suite-4.1/test-scenarios/004_basic_sanity.py", line 434, in snapshot_live_merge
    lambda: len(api.vms.get(VM0_NAME).snapshots.list()) == 2,
  File "/usr/lib/python2.7/site-packages/ovirtlago/testlib.py", line 264, in assert_true_within_long
    assert_equals_within_long(func, True, allowed_exceptions)
  File "/usr/lib/python2.7/site-packages/ovirtlago/testlib.py", line 251, in assert_equals_within_long
    func, value, LONG_TIMEOUT, allowed_exceptions=allowed_exceptions
  File "/usr/lib/python2.7/site-packages/ovirtlago/testlib.py", line 230, in assert_equals_within
    '%s != %s after %s seconds' % (res, value, timeout)
AssertionError: False != True after 600 seconds
2017-01-04 02:44:30,422::utils.py::_ret_via_queue::57::lago.utils::ERROR::Error while running thread
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 55, in _ret_via_queue
    queue.put({'return': func()})
  File "/home/jenkins/workspace/ovirt_4.1_system-tests/ovirt-system-tests/basic-suite-4.1/test-scenarios/004_basic_sanity.py", line 434, in snapshot_live_merge
    lambda: len(api.vms.get(VM0_NAME).snapshots.list()) == 2,
  File "/usr/lib/python2.7/site-packages/ovirtlago/testlib.py", line 264, in assert_true_within_long
    assert_equals_within_long(func, True, allowed_exceptions)
  File "/usr/lib/python2.7/site-packages/ovirtlago/testlib.py", line 251, in assert_equals_within_long
    func, value, LONG_TIMEOUT, allowed_exceptions=allowed_exceptions
  File "/usr/lib/python2.7/site-packages/ovirtlago/testlib.py", line 230, in assert_equals_within
    '%s != %s after %s seconds' % (res, value, timeout

**Comment by nvgoldin** [comment]
adding that in the log @landgraf  passed, there is also an error which was logged by nose in the xunit file, but did not appear in lago.log, which was the first error(in ost vm_run)

http://jenkins.ovirt.org/job/ovirt_4.1_system-tests/28/artifact/exported-artifacts/test_logs/basic-suite-4.1/post-004_basic_sanity.py/lago_logs/lago.log, but in http://jenkins.ovirt.org/job/ovirt_4.1_system-tests/28/artifact/exported-artifacts/nosetests-004_basic_sanity.py.xml:
```
<testcase classname="004_basic_sanity" name="vm_run" time="186.635"><failure type="exceptions.AssertionError" message="False != True after 180 seconds">Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python2.7/site-packages/ovirtlago/testlib.py", line 129, in wrapped_test
    test()
  File "/usr/lib/python2.7/site-packages/ovirtlago/testlib.py", line 59, in wrapper
    return func(get_test_prefix(), *args, **kwargs)
  File "/home/jenkins/workspace/ovirt_4.1_system-tests/ovirt-system-tests/basic-suite-4.1/test-scenarios/004_basic_sanity.py", line 348, in vm_run
    lambda: api.vms.get(VM0_NAME).status.state == 'up',
  File "/usr/lib/python2.7/site-packages/ovirtlago/testlib.py", line 260, in assert_true_within_short
    assert_equals_within_short(func, True, allowed_exceptions)
  File "/usr/lib/python2.7/site-packages/ovirtlago/testlib.py", line 244, in assert_equals_within_short
    func, value, SHORT_TIMEOUT, allowed_exceptions=allowed_exceptions
  File "/usr/lib/python2.7/site-packages/ovirtlago/testlib.py", line 230, in assert_equals_within
    '%s != %s after %s seconds' % (res, value, timeout)
AssertionError: False != True after 180 seconds
</failure></testcase>
```
I suspect this has to do with one of the tests running in parallel(``snapshot_merge``).
