### ISSUE TITLE
Random CI failues on _extract_paths_gfs method

### ISSUE THREAD

**Issue by nvgoldin** [lago-project/lago#439]
```python
21:33:58 not ok 49 ovirt.runtest: error in a test fails the run
21:33:58 # (from function `helpers.contains' in file tests/functional/helpers.bash, line 96,
21:33:58 #  in test file tests/functional/ovirt.runtest.bats, line 74)
21:33:58 #   `"$(cat $PREFIX/nosetests-$testfile.xml)" \' failed
21:33:58 # RUNNING:lago ovirt runtest /home/jenkins/workspace/lago_master_check-merged-fc25-x86_64/lago/tests/functional/fixtures/ovirt.runtest/001_basic_errored_test.py
21:33:58 # --output--
21:33:58 # current session does not belong to lago group.
21:33:58 # ovirt-role metadata entry will be soon deprecated, instead you should use the vm-provider entry in the domain definiton and set it no one of: ovirt-node, ovirt-engine, ovirt-host
21:33:58 # @ Run test: 001_basic_errored_test.py: 
21:33:58 # nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
21:33:58 #   # 001_basic_errored_test.test_error: 
21:33:58 #     * Collect artifacts: 
21:33:58 #       - [Thread-3] lago_functional_tests_host: ERROR (in 0:00:16)
21:33:58 # Error while running thread
21:33:58 # Traceback (most recent call last):
21:33:58 #   File "/usr/lib/python2.7/site-packages/lago/utils.py", line 55, in _ret_via_queue
21:33:58 #     queue.put({'return': func()})
21:33:58 #   File "/usr/lib/python2.7/site-packages/lago/prefix.py", line 1108, in _collect_artifacts
21:33:58 #     vm.collect_artifacts(path, ignore_nopath)
21:33:58 #   File "/usr/lib/python2.7/site-packages/lago/plugins/vm.py", line 496, in collect_artifacts
21:33:58 #     ignore_nopath=ignore_nopath
21:33:58 #   File "/usr/lib/python2.7/site-packages/lago/plugins/vm.py", line 311, in extract_paths
21:33:58 #     return self.provider.extract_paths(paths, *args, **kwargs)
21:33:58 #   File "/usr/lib/python2.7/site-packages/lago/vm.py", line 262, in extract_paths
21:33:58 #     self._extract_paths_gfs(paths=paths, ignore_nopath=ignore_nopath)
21:33:58 #   File "/usr/lib/python2.7/site-packages/lago/vm.py", line 517, in _extract_paths_gfs
21:33:58 #     gfs_cli.mount_ro(rootfs, '/')
21:33:58 #   File "/usr/lib64/python2.7/site-packages/guestfs.py", line 7414, in mount_ro
21:33:58 #     r = libguestfsmod.mount_ro(self._o, mountable, mountpoint)
21:33:58 # RuntimeError: mount_ro: /dev/sda3 on / (options: 'ro'): mount: /dev/sda3: can't read superblock
```

Not sure yet if this is the original reason(might be failing on something else, and then failing again when trying to extract the logs).

[1] http://jenkins.ovirt.org/job/lago_master_check-merged-fc25-x86_64/43/console

**Comment by nvgoldin** [comment]
1. I am unable to replicate this locally, so far I saw this only on CI, and on and off. 
2. The failure is is in the 'ovirt.runtest' functional test, which starts a fc23 VM, and executes several scenarios of `lago ovirt runtest`. On the last negative test, it attempts to collect logs, and for some reason ssh is unreachable and it falls back to libguestfs, which fails with the error:
```
RuntimeError: mount_ro: /dev/sda3 on / (options: 'ro'): mount: /dev/sda3: can't read superblock
```
3. Locally, ``lago collect`` works for me on the same fc23 image with sshd turned off(and I can see libguestfs extracts the logs properly).
4. In CI - the fc23 VM is provisioned in L3(hypervisor -> jenkins slave VM: lago under mock -> fc23 VM)
5. The "cirros" dhcp hack is not related - it still fails.
6. We are supposed to be using ``DIRECT`` backend for libguestfs, so I don't think libvirt is the reason.
7. This started around a week ago, so I can't think of any Lago changes which are related to this, my current *guess* is that the cause of the error is somewhere hiding between the combination of all the layers we're using(could be the VM OS/hypervisor OS/package changes in each one of them)
6. Changing to fc24 - seems to resolve this:
https://github.com/lago-project/lago/pull/443
http://jenkins.ovirt.org/job/lago_master_check-merged-fc24-x86_64/182/console
though, this is just one run.
