### ISSUE TITLE
Provide proper error message when lagocli is run in a wrong directory

### ISSUE THREAD

**Issue by mz-pdm** [lago-project/lago#451]
When lagocli is run outside the deployment directory, e.g. in ovirt-system-tests, it prints an error like

  % lagocli status
  Error occured, aborting
  Traceback (most recent call last):
    File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 872, in main
      cli_plugins[args.verb].do_run(args)
    File "/usr/lib/python2.7/site-packages/lago/plugins/cli.py", line 184, in do_run
      self._do_run(**vars(args))
    File "/usr/lib/python2.7/site-packages/lago/utils.py", line 477, in wrapper
      workdir_path = workdir_class.resolve_workdir_path(workdir_path)
    File "/usr/lib/python2.7/site-packages/lago/workdir.py", line 375, in resolve_workdir_path
      os.path.abspath(start_path)
  RuntimeError: Unable to find workdir for /home/pdm/ovirt/lago/ovirt-system-tests-tmp

It would be better if lagocli provided an intelligible error message giving the user a hint to switch to the deployment directory.

**Comment by nvgoldin** [comment]
@gbenhaim, I think this could be implemented easily once https://github.com/lago-project/lago/pull/401 gets in, using ``LagoUserException``
