### ISSUE TITLE
running 'lago ovirt status' after 'lago ovirt stop' hangs

### ISSUE THREAD

**Issue by eedri** [lago-project/lago#522]
Trying to run the lago demo tool with the following commands ( after extracting the image ) works:

- lago init
- lago ovirt start --with-vm
- lago ovirt status
- lago stop

But when running 'lago ovirt status' after the env is stopped, the commands hangs and eventually I had to run CTRL-C to stop it, got this exception:

lago ovirt status
Error occured, aborting
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ovirtlago/cmd.py", line 325, in do_run
    self.cli_plugins[args.ovirtverb].do_run(args)
  File "/usr/lib/python2.7/site-packages/lago/plugins/cli.py", line 184, in do_run
    self._do_run(**vars(args))
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 501, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 512, in wrapper
    return func(*args, prefix=prefix, **kwargs)
  File "/usr/lib/python2.7/site-packages/ovirtlago/cmd.py", line 211, in do_ovirt_status
    prefix.virt_env.engine_vm().status()
  File "/usr/lib/python2.7/site-packages/ovirtlago/utils.py", line 145, in wrapped_func
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ovirtlago/virt.py", line 463, in status
    api = self.get_api_v4(check=True)
  File "/usr/lib/python2.7/site-packages/ovirtlago/virt.py", line 301, in get_api_v4
    self._api_v4 = self._get_api(api_ver=4)
  File "/usr/lib/python2.7/site-packages/ovirtlago/virt.py", line 281, in _get_api
    raise RuntimeError('test api call failed')
RuntimeError: test api call failed

**Comment by mykaul** [comment]
I wonder if the problem is in the API's test() command - not sure it has a short enough timeout?
@machacekondra - any idea what is the timeout to the command?

**Comment by machacekondra** [comment]
I don't think so, the test() method return an answer according to traceback. But there is 60s until exception is raised. @eedri did you wait more then 60s?

**Comment by eedri** [comment]
Not that I can recall, but anyhow it doesn't make sense to wait 1 min for a status output,
So we need to check why it takes so long

**Comment by gbenhaim** [comment]
https://github.com/lago-project/lago-ost-plugin/issues/37 moved to lago-ost-plugin
