### ISSUE TITLE
lago collect failed with ExtractPathNoPathError despite having ignore_nopath=True by default

### ISSUE THREAD

**Issue by nvgoldin** [lago-project/lago#580]
http://jenkins.ovirt.org/job/ovirt-master_change-queue-tester/833/consoleFull
```
2017-06-21 07:46:00,857::cmd.py::main::947::cli::ERROR::Error occured, aborting
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 941, in main
    cli_plugins[args.verb].do_run(args)
  File "/usr/lib/python2.7/site-packages/lago/plugins/cli.py", line 184, in do_run
    self._do_run(**vars(args))
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 501, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 512, in wrapper
    return func(*args, prefix=prefix, **kwargs)
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 738, in do_collect
    prefix.collect_artifacts(output, ignore_nopath=not no_skip)
  File "/usr/lib/python2.7/site-packages/lago/sdk_utils.py", line 50, in wrapped
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/lago/log_utils.py", line 635, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/lago/prefix.py", line 1439, in collect_artifacts
    self.virt_env.get_vms().values(),
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 100, in invoke_in_parallel
    vt.join_all()
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 58, in _ret_via_queue
    queue.put({'return': func()})
  File "/usr/lib/python2.7/site-packages/lago/prefix.py", line 1435, in _collect_artifacts
    vm.collect_artifacts(path, ignore_nopath)
  File "/usr/lib/python2.7/site-packages/lago/plugins/vm.py", line 598, in collect_artifacts
    ignore_nopath=ignore_nopath
  File "/usr/lib/python2.7/site-packages/lago/plugins/vm.py", line 369, in extract_paths
    return self.provider.extract_paths(paths, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/lago/providers/libvirt/vm.py", line 299, in extract_paths
    ignore_nopath=ignore_nopath,
  File "/usr/lib/python2.7/site-packages/lago/plugins/vm.py", line 240, in extract_paths
    self._extract_paths_scp(paths=paths, ignore_nopath=ignore_nopath)
  File "/usr/lib/python2.7/site-packages/lago/plugins/vm.py", line 266, in _extract_paths_scp
    raise ExtractPathNoPathError(err.message)
ExtractPathNoPathError: scp: /var/log/fluentd/fluentdout.20170621.b552738936150792f: No such file or directory
C0644 8190068 fluentdout.20170621.q5527383034d3a5a1
```

From first look it seems like I misused ``str.endswith`` in the code there, but that is probably not the issue.

**Comment by nvgoldin** [comment]
So I think I found out what is wrong:
```
ExtractPathNoPathError: scp: /var/log/fluentd/fluentdout.20170623.b552a15b9cb15daa1: No such file or directory
C0644 8349007 fluentdout.20170623.q552a155a6b2c516a
```
We check if the exception message(as there is no explicit exceptions here - it just passes the channel stderr) - if it 'endswith' 'No such file or directory', while what it returned was also 'C0644 8349007 fluentdout.20170623.q552a155a6b2c516a' at the end. So moving it to regex matching should solve it.

However - I assume this happens due to a race condition- the file is deleted after it was discovered and before it was trasported. We try to extract the entire '/var/log' directory with the `scp`'s module `get` method with `recursive=True`. If we hit this failure early - we will just exit(after we fix the exception matching) - but we don't know if the other files were collected.

Avoiding that will require bigger refactoring:
1. First discovering the files, and saving the list.
2. Extracting them, and skipping files that are gone(if ignore_nopath=True).

For now I plan to begin with fixing the 'crash' - matching the exception message correctly. For the bigger fix - I'll open another issue.
