### ISSUE TITLE
 lago fails to initialize workspace - network

### ISSUE THREAD

**Issue by david-caro** [lago-project/lago#59]
Moved from https://bugzilla.redhat.com/show_bug.cgi?id=1272045

Description of problem:
Initializing workspace fails

Steps to Reproduce:
1.

    lagocli init /
    $PWD/testd-eployment /
    /usr/share/ovirtlago/config/virt/centos7.json /
    --template-repo-path=$PWD/lago-template-repositories/office.json

Actual results:

    2015-10-15 13:43:49,651 - root - DEBUG - Running command: qemu-img create -f qcow2 -b /home/tlitovsk/workspace/ci/lago_var/store/in_office_repo:centos7_host:v5 /home/tlitovsk/workspace/ci/lago_run/test-deployment/images/host0_root.qcow2
    2015-10-15 13:43:49,651 - root - DEBUG - Running command: ['qemu-img', 'create', '-f', 'qcow2', '-b', u'/home/tlitovsk/workspace/ci/lago_var/store/in_office_repo:centos7_host:v5', u'/home/tlitovsk/workspace/ci/lago_run/test-deployment/images/host0_root.qcow2']
    2015-10-15 13:43:49,750 - root - DEBUG - command exit with 0
    2015-10-15 13:43:49,751 - root - DEBUG - command stdout: Formatting '/home/tlitovsk/workspace/ci/lago_run/test-deployment/images/host0_root.qcow2', fmt=qcow2 size=53687091200 backing_file='/home/tlitovsk/workspace/ci/lago_var/store/in_office_repo:centos7_host:v5' encryption=off cluster_size=65536 lazy_refcounts=off refcount_bits=16
    
    2015-10-15 13:43:49,751 - root - INFO - Successfully created disk at /home/tlitovsk/workspace/ci/lago_run/test-deployment/images/host0_root.qcow2
    2015-10-15 13:43:49,753 - root - ERROR - Error occured, aborting
    Traceback (most recent call last):
      File "/usr/bin/lagocli", line 531, in main
        func(args)
      File "/usr/bin/lagocli", line 78, in do_init
        prefix.virt_conf(virt_conf, repo, store)
      File "/usr/lib/python2.7/site-packages/lago/__init__.py", line 348, in virt_conf
        self._config_net_topology(conf)
      File "/usr/lib/python2.7/site-packages/lago/__init__.py", line 220, in _config_net_topology
        self._allocate_ips_to_nics(conf)
      File "/usr/lib/python2.7/site-packages/lago/__init__.py", line 202, in _allocate_ips_to_nics
        net['gw'],
    KeyError: 'gw'

Expected results:
success

Additional info:
version : lago-0.2-153_g948690d.fc22.noarch.rpm

Yaniv Bronhaim 2015-10-22 06:50:30 EDT

>we don't always have gw declared in the specific net value. here you use :
>
    "nets": {
        "lago": {
            "type": "nat",
            "dhcp": {
                "start": 100,
                "end": 254
            },
            "management": true
        }
    }

>which does not state the gateway - so we should use default value in `lago/__init__.py` line 202
>its part of commit lago@59411f1
>
                vacant = _create_ip(                                            
                    net['gw'],                                                  
                    set(range(2, 255)).difference(                              
                        set(                                                    
                            [                                                   
                                int(ip.split('.')[-1]) for ip in allocated      
                            ]                                                   
                        )                                                       
                    ).pop()                                                     
                )   
>

**Comment by david-caro** [comment]
I can't reproduce

**Comment by sabose** [comment]
@david-caro I'm running into this issue as well, I followed steps to setup lago as per http://lago.readthedocs.io/en/latest/README.html, and on running ./run_suite.sh basic_suite_3.6 -->

@ Initialize and populate prefix: ERROR (in 0:00:01)
Error occured, aborting
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 691, in main
    cli_plugins[args.verb].do_run(args)
  File "/usr/lib/python2.7/site-packages/lago/plugins/cli.py", line 180, in do_run
    self._do_run(**vars(args))
  File "/usr/lib/python2.7/site-packages/lago/log_utils.py", line 615, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 181, in do_init
    do_bootstrap=not skip_bootstrap,
  File "/usr/lib/python2.7/site-packages/lago/prefix.py", line 824, in virt_conf_from_stream
    do_bootstrap=do_bootstrap,
  File "/usr/lib/python2.7/site-packages/lago/prefix.py", line 933, in virt_conf
    conf = self._config_net_topology(conf)
  File "/usr/lib/python2.7/site-packages/lago/prefix.py", line 437, in _config_net_topology
    self._allocate_ips_to_nics(conf)
  File "/usr/lib/python2.7/site-packages/lago/prefix.py", line 409, in _allocate_ips_to_nics
    net['gw'], set(range(2, 255)).difference(
KeyError: 'gw'

**Comment by david-caro** [comment]
Which version of lago are you using? (rpm -q lago)
Also, can you check the permissions at /var/lib/lago/*? The user which you are running the suite with should have access there (either by the group or the user permission, usually by the group one).
If you just added your user to the lago group, remember that you have to log out and in (or run newgrp lago, or similar) for the changes to take effect, you can verify running `id`, it should show the lago group there.

**Comment by sabose** [comment]
rpm - lago-0.19.0-1.fc22.noarch

I edited /etc/lago.d/lago.conf to point to a directory under my /home account. 
and yes "id <user>" does show the lago and qemu groups.

Another note - I do see there are files under /home/user/lago/store , so not a permission issue?

**Comment by david-caro** [comment]
can you try updating to latest? we are at around 0.23 iirc.

There was an issue that resulted in that same error whenever it was unable to create /access the leases file for the network (the real error was being swallowed). I think it was #20

**Comment by david-caro** [comment]
Upgrading might reveal the real error :)

**Comment by sabose** [comment]
Yes, thanks, it did! and indeed it was a permission issue at /var/lib/lago/ (i had earlier checked with id <user>, but had to log out for the settings to take effect). Thanks for help

Note: upgrade from repo (http://resources.ovirt.org/repos/lago/stable/0.0/rpm/fc23) did not work - had to manually download and update rpms
