### ISSUE TITLE
TypeError when running `lago list`

### ISSUE THREAD

**Issue by d3dave** [lago-project/lago#620]
```
$ lago list prefixes
Error occured, aborting
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/lago/cmd.py", line 941, in main
    cli_plugins[args.verb].do_run(args)
  File "/usr/local/lib/python2.7/dist-packages/lago/plugins/cli.py", line 184, in do_run
    self._do_run(**vars(args))
  File "/usr/local/lib/python2.7/dist-packages/lago/utils.py", line 501, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/lago/utils.py", line 512, in wrapper
    return func(*args, prefix=prefix, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/lago/cmd.py", line 631, in do_list
    workdir.load()
  File "/usr/local/lib/python2.7/dist-packages/lago/workdir.py", line 158, in load
    basepath, dirs, _ = os.walk(self.path).next()
  File "/usr/lib/python2.7/os.py", line 278, in walk
    names = listdir(top)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```
Same with `list envs`...

**Comment by nvgoldin** [comment]
Thanks for reporting this. I think we already had a ticket about that, but can't find it at the moment. From what I recall, we talked about deprecating the ``lago list`` command or replacing it with something more flexible. @gbenhaim - what do you think?

**Comment by gbenhaim** [comment]
Agree, ```lago list``` should be removed.

**Comment by gbenhaim** [comment]
https://github.com/lago-project/lago/pull/628

**Comment by gbenhaim** [comment]
fixed https://github.com/lago-project/lago/pull/628
