### ISSUE TITLE
python-devel packages is needed for installing lago with pip

### ISSUE THREAD

**Issue by gbenhaim** [lago-project/lago#625]
From centos 7.3 machine:

```
[root@vm0-server ~]# pip install lago
Collecting lago
  Using cached lago-0.40.0.tar.gz
    Complete output from command python setup.py egg_info:
    dulwich/_objects.c:21:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5iY8dV/lago/setup.py", line 62, in <module>
        pbr=True,
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 618, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 862, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 874, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 339, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 623, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 653, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 849, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1130, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1118, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5iY8dV/lago/
[root@vm0-server ~]# yum install python-devel
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.joinweb.co.il
 * epel: mirror.nonstop.co.il
 * extras: centos.joinweb.co.il
 * updates: centos.joinweb.co.il
Resolving Dependencies
--> Running transaction check
---> Package python-devel.x86_64 0:2.7.5-48.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===============================================================================================================================================
 Package                              Arch                           Version                                Repository                    Size
===============================================================================================================================================
Installing:
 python-devel                         x86_64                         2.7.5-48.el7                           base                         393 k

Transaction Summary
===============================================================================================================================================
Install  1 Package

Total download size: 393 k
Installed size: 1.0 M
Is this ok [y/d/N]: y
Downloading packages:
python-devel-2.7.5-48.el7.x86_64.rpm                                                                                    | 393 kB  00:00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : python-devel-2.7.5-48.el7.x86_64                                                                                            1/1 
  Verifying  : python-devel-2.7.5-48.el7.x86_64                                                                                            1/1 

Installed:
  python-devel.x86_64 0:2.7.5-48.el7                                                                                                           

Complete!
[root@vm0-server ~]# pip install lago
Collecting lago
  Using cached lago-0.40.0.tar.gz
Collecting configparser (from lago)
  Downloading configparser-3.5.0.tar.gz
Collecting enum34 (from lago)
  Downloading enum34-1.1.6-py2-none-any.whl
Collecting libvirt-python (from lago)
  Downloading libvirt-python-3.4.0.tar.gz (181kB)
    100% |████████████████████████████████| 184kB 742kB/s 
Collecting lockfile (from lago)
  Downloading lockfile-0.12.2-py2.py3-none-any.whl
Collecting lxml (from lago)
  Downloading lxml-3.8.0-cp27-cp27mu-manylinux1_x86_64.whl (6.8MB)
    100% |████████████████████████████████| 6.8MB 161kB/s 
Collecting paramiko (from lago)
  Downloading paramiko-2.2.1-py2.py3-none-any.whl (176kB)
    100% |████████████████████████████████| 184kB 392kB/s 
Collecting pbr (from lago)
  Downloading pbr-3.1.1-py2.py3-none-any.whl (99kB)
    100% |████████████████████████████████| 102kB 377kB/s 
Collecting pyxdg (from lago)
  Downloading pyxdg-0.25.tar.gz (48kB)
    100% |████████████████████████████████| 51kB 383kB/s 
Collecting PyYAML (from lago)
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 321kB/s 
Collecting scp (from lago)
  Downloading scp-0.10.2-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /usr/lib/python2.7/site-packages (from lago)
Collecting stevedore (from lago)
  Downloading stevedore-1.23.0-py2.py3-none-any.whl
Collecting wrapt (from lago)
  Downloading wrapt-1.10.10.tar.gz
Collecting Jinja2 (from lago)
  Downloading Jinja2-2.9.6-py2.py3-none-any.whl (340kB)
    100% |████████████████████████████████| 348kB 480kB/s 
Collecting xmltodict (from lago)
  Downloading xmltodict-0.11.0-py2.py3-none-any.whl
Collecting netaddr (from lago)
  Downloading netaddr-0.7.19-py2.py3-none-any.whl (1.6MB)
    100% |████████████████████████████████| 1.6MB 494kB/s 
Collecting cryptography>=1.1 (from paramiko->lago)
  Downloading cryptography-1.9.tar.gz (409kB)
    100% |████████████████████████████████| 419kB 884kB/s 
Collecting bcrypt>=3.1.3 (from paramiko->lago)
  Downloading bcrypt-3.1.3-cp27-cp27mu-manylinux1_x86_64.whl (57kB)
    100% |████████████████████████████████| 61kB 999kB/s 
Collecting pyasn1>=0.1.7 (from paramiko->lago)
  Downloading pyasn1-0.2.3-py2.py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 963kB/s 
Collecting pynacl>=1.0.1 (from paramiko->lago)
  Downloading PyNaCl-1.1.2-cp27-cp27mu-manylinux1_x86_64.whl (539kB)
    100% |████████████████████████████████| 542kB 533kB/s 
Collecting six>=1.9.0 (from stevedore->lago)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2->lago)
  Downloading MarkupSafe-1.0.tar.gz
Collecting idna>=2.1 (from cryptography>=1.1->paramiko->lago)
  Downloading idna-2.5-py2.py3-none-any.whl (55kB)
    100% |████████████████████████████████| 61kB 944kB/s 
Collecting asn1crypto>=0.21.0 (from cryptography>=1.1->paramiko->lago)
  Downloading asn1crypto-0.22.0-py2.py3-none-any.whl (97kB)
    100% |████████████████████████████████| 102kB 827kB/s 
Collecting ipaddress (from cryptography>=1.1->paramiko->lago)
  Downloading ipaddress-1.0.18-py2-none-any.whl
Collecting cffi>=1.7 (from cryptography>=1.1->paramiko->lago)
  Downloading cffi-1.10.0-cp27-cp27mu-manylinux1_x86_64.whl (392kB)
    100% |████████████████████████████████| 399kB 841kB/s 
Collecting pycparser (from cffi>=1.7->cryptography>=1.1->paramiko->lago)
  Downloading pycparser-2.17.tar.gz (231kB)
    100% |████████████████████████████████| 235kB 993kB/s 
Installing collected packages: configparser, enum34, libvirt-python, lockfile, lxml, idna, asn1crypto, six, ipaddress, pycparser, cffi, cryptography, bcrypt, pyasn1, pynacl, paramiko, pbr, pyxdg, PyYAML, scp, stevedore, wrapt, MarkupSafe, Jinja2, xmltodict, netaddr, lago
  Running setup.py install for configparser ... done
  Running setup.py install for libvirt-python ... done
  Running setup.py install for pycparser ... done
  Running setup.py install for cryptography ... done
  Running setup.py install for pyxdg ... done
  Running setup.py install for PyYAML ... done
  Running setup.py install for wrapt ... done
  Running setup.py install for MarkupSafe ... done
  Running setup.py install for lago ... done
Successfully installed Jinja2-2.9.6 MarkupSafe-1.0 PyYAML-3.12 asn1crypto-0.22.0 bcrypt-3.1.3 cffi-1.10.0 configparser-3.5.0 cryptography-1.9 enum34-1.1.6 idna-2.5 ipaddress-1.0.18 lago-0.40.0- libvirt-python-3.4.0 lockfile-0.12.2 lxml-3.8.0 netaddr-0.7.19 paramiko-2.2.1 pbr-3.1.1 pyasn1-0.2.3 pycparser-2.17 pynacl-1.1.2 pyxdg-0.25 scp-0.10.2 six-1.10.0 stevedore-1.23.0 wrapt-1.10.10 xmltodict-0.11.0
```

**Comment by gbenhaim** [comment]
@nvgoldin Did you encounter this issue before?

**Comment by nvgoldin** [comment]
Yep. Though I thought this was pulled with with python-pip, guess not. Seems like it is ``dulwich`` which requires it. 
Also wondering if distributing the ``wheel`` would resolve this.

**Comment by nvgoldin** [comment]
https://www.dulwich.io/docs/#installation

>If you don’t want to install the C bindings, specify the –pure argument to setup.py:
$ python setup.py --pure install
or if you are installing from pip:
$ pip install dulwich --global-option="--pure"


Need to check if we can to the global option, I know pip supports this, I do not know if pbr<->setuptool does.

**Comment by gbenhaim** [comment]
For the meanwhile, I'll add it to the docs.
