### ISSUE TITLE
Error on prefix cleanup after init failure

### ISSUE THREAD

**Issue by david-caro** [lago-project/lago#65]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 535, in main
    cli_plugins[args.verb].do_run(args)
  File "/usr/lib/python2.7/site-packages/lago/plugins/cli.py", line 169, in do_run
    self._do_run(**vars(args))
  File "/usr/lib/python2.7/site-packages/lago/log_utils.py", line 599, in wrapper
    func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 119, in do_init
    shutil.rmtree(prefix)
  File "/usr/lib64/python2.7/shutil.py", line 228, in rmtree
    if os.path.islink(path):
  File "/usr/lib64/python2.7/posixpath.py", line 135, in islink
    st = os.lstat(path)
TypeError: coercing to Unicode: need string or buffer, Prefix found

**Comment by david-caro** [comment]
This was already solved at fb56df35129aea83d8e81e41a347173edcde57b6
