### ISSUE TITLE
TimerException: ('Unable to acquire lock for %s in %s secs', u'/var/lib/lago/repolock', 180)

### ISSUE THREAD

**Issue by dron1** [lago-project/lago#669]
we have failures in ovirt testing with an error from lago: 
TimerException: ('Unable to acquire lock for %s in %s secs', u'/var/lib/lago/repolock', 180)

here is the lago log from one of the failed jobs: 
https://pastebin.com/1pLJ9SUa

here is exception: 

2017-11-07 21:15:03,777::utils.py::__enter__::391::lago.utils::DEBUG::Acquiring lock for /var/lib/lago/repolock
2017-11-07 21:18:03,777::reposetup.py::sync_rpm_repository::238::ovirtlago.reposetup::DEBUG::Removing temp cache dir /tmp/reposync_D1lAoI
2017-11-07 21:18:03,777::log_utils.py::end_log_task::670::root::ERROR::    * Running reposync: [31mERROR[0m (in 0:03:00)
2017-11-07 21:18:03,779::log_utils.py::__exit__::607::ovirtlago.reposetup::DEBUG::  File "/usr/lib/python2.7/site-packages/ovirtlago/reposetup.py", line 191, in sync_rpm_repository
    with LockFile(lock_path, timeout=180):
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 397, in __enter__
    self.timeout,

2017-11-07 21:18:03,779::log_utils.py::end_log_task::670::root::ERROR::  # Syncing remote repos locally (this might take some time): [31mERROR[0m (in 0:03:00)
2017-11-07 21:18:03,779::log_utils.py::__exit__::607::ovirtlago.prefix::DEBUG::  File "/usr/lib/python2.7/site-packages/ovirtlago/prefix.py", line 140, in prepare_repo
    repos,
  File "/usr/lib/python2.7/site-packages/ovirtlago/reposetup.py", line 191, in sync_rpm_repository
    with LockFile(lock_path, timeout=180):
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 397, in __enter__
    self.timeout,

2017-11-07 21:18:03,780::log_utils.py::end_log_task::670::root::ERROR::@ Create prefix internal repo: [31mERROR[0m (in 0:03:00)
2017-11-07 21:18:03,780::log_utils.py::__exit__::607::ovirtlago.prefix::DEBUG::  File "/usr/lib/python2.7/site-packages/lago/log_utils.py", line 636, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ovirtlago/prefix.py", line 140, in prepare_repo
    repos,
  File "/usr/lib/python2.7/site-packages/ovirtlago/reposetup.py", line 191, in sync_rpm_repository
    with LockFile(lock_path, timeout=180):
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 397, in __enter__
    self.timeout,

2017-11-07 21:18:03,781::cmd.py::do_run::365::root::ERROR::Error occured, aborting
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ovirtlago/cmd.py", line 362, in do_run
    self.cli_plugins[args.ovirtverb].do_run(args)
  File "/usr/lib/python2.7/site-packages/lago/plugins/cli.py", line 184, in do_run
    self._do_run(**vars(args))
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 501, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 512, in wrapper
    return func(*args, prefix=prefix, **kwargs)
  File "/usr/lib/python2.7/site-packages/ovirtlago/cmd.py", line 158, in do_ovirt_reposetup
    repoman_config=repoman_config,
  File "/usr/lib/python2.7/site-packages/lago/log_utils.py", line 636, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ovirtlago/prefix.py", line 140, in prepare_repo
    repos,
  File "/usr/lib/python2.7/site-packages/ovirtlago/reposetup.py", line 191, in sync_rpm_repository
    with LockFile(lock_path, timeout=180):
  File "/usr/lib/python2.7/site-packages/lago/utils.py", line 397, in __enter__
    self.timeout,
TimerException: ('Unable to acquire lock for %s in %s secs', u'/var/lib/lago/repolock', 180)

**Comment by mykaul** [comment]
- Is this on a specific host?
- And is indeed the lock is taken? And can you manually delete it and retry?
Y.

**Comment by dron1** [comment]
I found 2 servers so far.
on both hosts we could not find a running processes, or a lock file
under /var/lib/lago/

**Comment by mykaul** [comment]
On Thu, Nov 9, 2017 at 2:59 PM, Dafna Ron <notifications@github.com> wrote:

> I found 2 servers so far.
> on both hosts we could not find a running processes, or a lock file
> under /var/lib/lago/


And no permission issues?
Y.

**Comment by dron1** [comment]
I do not see anything related or problematic in secure log or in messages.

the only thing that even slightly looked odd to me was a warning in
messages log around the time of the failure:

Nov  9 12:16:05 ovirt-srv04 libvirtd: 2017-11-09 12:16:05.937+0000:
15164: warning : qemuDomainObjTaint:4443 : Domain id=2
name='50d545da-lago-basic-suite-master-host-1'
uuid=f8414bc5-f3c7-4657-b750-0a1a983e4242 is tainted: host-cpu

The domains themselves simply show the same line 'is tainted: host-cpu'
before terminated.

**Comment by gbenhaim** [comment]
My guess is that the issue occurs when the build in Jenkins is aborted (either manually or by timeout).
https://wiki.jenkins.io/display/JENKINS/Aborting+a+build

This https://github.com/lago-project/lago/pull/670 should fix the issue.
