### ISSUE TITLE
After upgrade to F28 beta: Lago RPMs get downgraded to fc25 (0.42) 

### ISSUE THREAD

**Issue by mykaul** [lago-project/lago#709]
Running OST, and now it fails.
I can't think of anything other than the upgrade from F27 to F28:

+ local template_repo=/home/ykaul/ovirt-system-tests/basic-suite-master/template-repo.json
+ local initfile=/home/ykaul/ovirt-system-tests/basic-suite-master/LagoInitFile
+ lago init /home/ykaul/ovirt-system-tests/deployment-basic-suite-master /home/ykaul/ovirt-system-tests/basic-suite-master/LagoInitFile --template-repo-path /home/ykaul/ovirt-system-tests/basic-suite-master/template-repo.json
@ Initialize and populate prefix: 
@ Initialize and populate prefix: ERROR (in 0:00:00)
Error occured, aborting
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 965, in main
    cli_plugins[args.verb].do_run(args)
  File "/usr/lib/python2.7/site-packages/lago/plugins/cli.py", line 184, in do_run
    self._do_run(**vars(args))
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 164, in do_init
    prefix = workdir.add_prefix(prefix_name)
  File "/usr/lib/python2.7/site-packages/lago/workdir.py", line 70, in decorator
    workdir.load()
  File "/usr/lib/python2.7/site-packages/lago/workdir.py", line 183, in load
    '"%s/current" should exist and be a soft link' % self.path
MalformedWorkdir: "/home/ykaul/ovirt-system-tests/deployment-basic-suite-master/current" should exist and be a soft link

[ykaul@ykaul ovirt-system-tests]$ cd deployment-basic-suite-master/
[ykaul@ykaul deployment-basic-suite-master]$ ls -l
total 0

**Comment by mykaul** [comment]
Solved - for some odd reason, I got OLD lago version (fc25...?!)
'make rpm' and installed the latest and it was solved. Strange.

**Comment by mykaul** [comment]
That can explain it:
[ykaul@ykaul noarch]$ sudo grep lago /var/log/dnf.rpm.log
2018-04-18T07:14:13Z INFO Downgraded: python-lago-0.42.0-1.fc25.noarch
2018-04-18T07:14:13Z INFO Downgraded: lago-0.42.0-1.fc25.noarch
2018-04-18T07:25:55Z INFO Downgraded: python-lago-0.42.0-1.fc25.noarch
2018-04-18T07:25:55Z INFO Downgraded: lago-0.42.0-1.fc25.noarch
2018-04-18T07:30:05Z INFO Erased: lago-0.43.1-1.fc27.noarch
2018-04-18T07:31:05Z INFO Erased: python-lago-0.43.1-1.fc27.noarch
2018-04-18T08:41:44Z INFO Upgraded: python-lago-0.43.1-1.fc28.noarch
2018-04-18T08:41:44Z INFO Upgraded: lago-0.43.1-1.fc28.noarch
2018-04-18T08:41:44Z INFO Cleanup: lago-0.42.0-1.fc25.noarch
2018-04-18T08:41:44Z INFO Cleanup: python-lago-0.42.0-1.fc25.noarch

**Comment by gbenhaim** [comment]
Can I close this one?
