### ISSUE TITLE
Full Traceback on cp-from-vm error

### ISSUE THREAD

**Issue by enarha** [lago-project/lago#740]
Full traceback is printed out on cp-from-vm exception.
A short error message should be enough.
To reproduce, try to cp-from-vm non existent file from the vm.

**Comment by gbenhaim** [comment]
This is also true when trying to copy a directory, and during the file transfer, one of the files in the directory is deleted. For example (lago tried to collect `/etc/httpd`):

```
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64] @ Collect artifacts: ERROR (in 0:00:04)
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64] Error occured, aborting
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64] Traceback (most recent call last):
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]   File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 969, in main
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]     cli_plugins[args.verb].do_run(args)
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]   File "/usr/lib/python2.7/site-packages/lago/plugins/cli.py", line 184, in do_run
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]     self._do_run(**vars(args))
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]   File "/usr/lib/python2.7/site-packages/lago/utils.py", line 505, in wrapper
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]     return func(*args, **kwargs)
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]   File "/usr/lib/python2.7/site-packages/lago/utils.py", line 516, in wrapper
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]     return func(*args, prefix=prefix, **kwargs)
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]   File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 752, in do_collect
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]     prefix.collect_artifacts(output, ignore_nopath=not no_skip)
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]   File "/usr/lib/python2.7/site-packages/lago/sdk_utils.py", line 50, in wrapped
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]     return func(*args, **kwargs)
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]   File "/usr/lib/python2.7/site-packages/lago/log_utils.py", line 636, in wrapper
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]     return func(*args, **kwargs)
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]   File "/usr/lib/python2.7/site-packages/lago/prefix.py", line 1528, in collect_artifacts
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]     self.virt_env.get_vms().values(),
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]   File "/usr/lib/python2.7/site-packages/lago/utils.py", line 100, in invoke_in_parallel
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]     return vt.join_all()
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]   File "/usr/lib/python2.7/site-packages/lago/utils.py", line 58, in _ret_via_queue
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]     queue.put({'return': func()})
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]   File "/usr/lib/python2.7/site-packages/lago/prefix.py", line 1524, in _collect_artifacts
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]     vm.collect_artifacts(path, ignore_nopath)
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]   File "/usr/lib/python2.7/site-packages/lago/plugins/vm.py", line 644, in collect_artifacts
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]     ignore_nopath=ignore_nopath
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]   File "/usr/lib/python2.7/site-packages/lago/plugins/vm.py", line 384, in extract_paths
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]     return self.provider.extract_paths(paths, *args, **kwargs)
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]   File "/usr/lib/python2.7/site-packages/lago/providers/libvirt/vm.py", line 398, in extract_paths
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]     ignore_nopath=ignore_nopath,
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]   File "/usr/lib/python2.7/site-packages/lago/plugins/vm.py", line 249, in extract_paths
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]     self._extract_paths_scp(paths=paths, ignore_nopath=ignore_nopath)
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]   File "/usr/lib/python2.7/site-packages/lago/plugins/vm.py", line 83, in wrapper
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]     return func(self, *args, **kwargs)
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]   File "/usr/lib/python2.7/site-packages/lago/plugins/vm.py", line 269, in _extract_paths_scp
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]     propagate_fail=False
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]   File "/usr/lib/python2.7/site-packages/lago/plugins/vm.py", line 428, in copy_from
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]     local_path=local_path,
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]   File "/usr/lib/python2.7/site-packages/scp.py", line 125, in get
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]     self._recv_all()
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]   File "/usr/lib/python2.7/site-packages/scp.py", line 257, in _recv_all
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64]     raise SCPException(str(msg).strip())
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64] SCPException: scp: /etc/httpd/run/cgisock.28243: No such device or address
14:23:00 [check-patch.basic_fc_suite_master.el7.x86_64] C0644 6 httpd.pid
```

**Comment by gbenhaim** [comment]
The fix should also handle errors in `lago copy-to-vm`.
