### ISSUE TITLE
 copy-from-vm traceback a message if host to copy from is down - need to write nice message instead

### ISSUE THREAD

**Issue by galitf** [lago-project/lago#748]
lago copy-from-vm vm-el7 /root/etc/hosts gal
Error occured, aborting
Traceback (most recent call last):
  File "/home/grosenth/projects/lago/lago/cmd.py", line 969, in main
    cli_plugins[args.verb].do_run(args)
  File "/home/grosenth/projects/lago/lago/plugins/cli.py", line 184, in do_run
    self._do_run(**vars(args))
  File "/home/grosenth/projects/lago/lago/utils.py", line 505, in wrapper
    return func(*args, **kwargs)
  File "/home/grosenth/projects/lago/lago/utils.py", line 516, in wrapper
    return func(*args, prefix=prefix, **kwargs)
  File "/home/grosenth/projects/lago/lago/cmd.py", line 684, in do_copy_from_vm
    'Host %s is not "running", but "%s"' % (host.name(), host.state())
RuntimeError: Host vm-el7 is not "running", but "down"

**Comment by galitf** [comment]
also happens with copy-to-vm when the vm is down
needs to fix as well

lago copy-from-vm  vm-el7  /root/ga1 /root/gal2
Error occured, aborting
Traceback (most recent call last):
  File "/home/grosenth/projects/lago/lago/cmd.py", line 969, in main
    cli_plugins[args.verb].do_run(args)
  File "/home/grosenth/projects/lago/lago/plugins/cli.py", line 184, in do_run
    self._do_run(**vars(args))
  File "/home/grosenth/projects/lago/lago/utils.py", line 505, in wrapper
    return func(*args, **kwargs)
  File "/home/grosenth/projects/lago/lago/utils.py", line 516, in wrapper
    return func(*args, prefix=prefix, **kwargs)
  File "/home/grosenth/projects/lago/lago/cmd.py", line 684, in do_copy_from_vm
    'Host %s is not "running", but "%s"' % (host.name(), host.state())
RuntimeError: Host vm-el7 is not "running", but "down"
