### ISSUE TITLE
Lago fails to run after upgrade to F29 beta - MalformedWorkdir: "/home/ykaul/ovirt-system-tests/deployment-basic-suite-master/current" should exist and be a soft link

### ISSUE THREAD

**Issue by mykaul** [lago-project/lago#764]
```
+ lago init /home/ykaul/ovirt-system-tests/deployment-basic-suite-master /home/ykaul/ovirt-system-tests/basic-suite-master/LagoInitFile --template-repo-path /home/ykaul/ovirt-system-tests/basic-suite-master/template-repo.json
@ Initialize and populate prefix: 
@ Initialize and populate prefix: ERROR (in 0:00:00)
Error occured, aborting
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 965, in main
    cli_plugins[args.verb].do_run(args)
  File "/usr/lib/python2.7/site-packages/lago/plugins/cli.py", line 184, in do_run
    self._do_run(**vars(args))
  File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 164, in do_init
    prefix = workdir.add_prefix(prefix_name)
  File "/usr/lib/python2.7/site-packages/lago/workdir.py", line 70, in decorator
    workdir.load()
  File "/usr/lib/python2.7/site-packages/lago/workdir.py", line 183, in load
    '"%s/current" should exist and be a soft link' % self.path
MalformedWorkdir: "/home/ykaul/ovirt-system-tests/deployment-basic-suite-master/current" should exist and be a soft link
+ on_exit
+ [[ 1 -ne 0 ]]
+ logger.error 'on_exit: Exiting with a non-zero status'
+ logger.log ERROR 'on_exit: Exiting with a non-zero status'
+ set +x
2018-09-27 11:58:24.791831445+0300 run_suite.sh::on_exit::ERROR:: on_exit: Exiting with a non-zero status
+ logger.info 'Dumping lago env status'
```

**Comment by mykaul** [comment]
Closing - upgraded to a newer release and it seems to work.
